# Generated by Django 5.0.2 on 2024-04-17 10:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('esclavizados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_evento', models.CharField(max_length=70, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SituacionLugar',
            fields=[
                ('situacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documental', models.CharField(max_length=70, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lugar', models.CharField(max_length=70, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposInstitucion',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='placehistorical',
            name='lugar',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='fecha_final_factual',
            new_name='fecha_final_aproximada',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='fecha_inicial_factual',
            new_name='fecha_inicial_aproximada',
        ),
        migrations.RenameField(
            model_name='historicaldocumento',
            old_name='fecha_final_factual',
            new_name='fecha_final_aproximada',
        ),
        migrations.RenameField(
            model_name='historicaldocumento',
            old_name='fecha_inicial_factual',
            new_name='fecha_inicial_aproximada',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalugarrel',
            name='anterior_posterior',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalugarrel',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalugarrel',
            name='relacion_lugar',
        ),
        migrations.RemoveField(
            model_name='historicalpersonanoesclavizada',
            name='rol_evento',
        ),
        migrations.RemoveField(
            model_name='historicalpersonarelaciones',
            name='persona1',
        ),
        migrations.RemoveField(
            model_name='historicalpersonarelaciones',
            name='persona2',
        ),
        migrations.RemoveField(
            model_name='personalugarrel',
            name='anterior_posterior',
        ),
        migrations.RemoveField(
            model_name='personalugarrel',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='personalugarrel',
            name='relacion_lugar',
        ),
        migrations.RemoveField(
            model_name='personanoesclavizada',
            name='rol_evento',
        ),
        migrations.RemoveField(
            model_name='personarelaciones',
            name='persona1',
        ),
        migrations.RemoveField(
            model_name='personarelaciones',
            name='persona2',
        ),
        migrations.AddField(
            model_name='documento',
            name='deteriorado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='deteriorado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicallugar',
            name='otros_nombres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersona',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonaesclavizada',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonaesclavizada',
            name='procedencia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esclavizados.lugar'),
        ),
        migrations.AddField(
            model_name='historicalpersonaesclavizada',
            name='procedencia_adicional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonaesclavizada',
            name='salud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonalugarrel',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonanoesclavizada',
            name='entidad_asociada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpersonanoesclavizada',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonarelaciones',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='otros_nombres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personaesclavizada',
            name='procedencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedencia_persona_esclavizada', to='esclavizados.lugar'),
        ),
        migrations.AddField(
            model_name='personaesclavizada',
            name='procedencia_adicional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personaesclavizada',
            name='salud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalugarrel',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personalugarrel',
            name='personas',
            field=models.ManyToManyField(related_name='p_x_l_pere', to='esclavizados.persona'),
        ),
        migrations.AddField(
            model_name='personanoesclavizada',
            name='entidad_asociada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personarelaciones',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personarelaciones',
            name='personas',
            field=models.ManyToManyField(related_name='relaciones', to='esclavizados.persona'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='actividad',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre_abreviado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calidades',
            name='calidad',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='folio_inicial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='etonimos',
            name='etonimo',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='hispanizaciones',
            name='hispanizacion',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalarchivo',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalarchivo',
            name='nombre_abreviado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='folio_inicial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicallugar',
            name='tipo',
            field=models.CharField(choices=[('ciudad', 'Ciudad'), ('pueblo', 'Pueblo'), ('estado', 'Estado'), ('gobernacion', 'Gobernación'), ('pais', 'País'), ('provincia', 'Provincia'), ('villa', 'Villa'), ('real', 'Real de Minas'), ('parroquia', 'Parroquia'), ('fuerte', 'Fuerte'), ('puerto', 'Puerto'), ('isla', 'Isla'), ('region', 'Región'), ('diocesis', 'Diócesis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpersonalugarrel',
            name='ordinal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(choices=[('ciudad', 'Ciudad'), ('pueblo', 'Pueblo'), ('estado', 'Estado'), ('gobernacion', 'Gobernación'), ('pais', 'País'), ('provincia', 'Provincia'), ('villa', 'Villa'), ('real', 'Real de Minas'), ('parroquia', 'Parroquia'), ('fuerte', 'Fuerte'), ('puerto', 'Puerto'), ('isla', 'Isla'), ('region', 'Región'), ('diocesis', 'Diócesis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalugarrel',
            name='ordinal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Corporacion',
            fields=[
                ('corporacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('corporacion_idno', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_institucion', models.CharField(max_length=100, unique=True)),
                ('nombres_alternativos', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documentos', models.ManyToManyField(to='esclavizados.documento')),
                ('personas_asociadas', models.ManyToManyField(blank=True, to='esclavizados.persona')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('tipo_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esclavizados.tiposinstitucion')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='entidades_asociadas',
            field=models.ManyToManyField(blank=True, to='esclavizados.corporacion'),
        ),
        migrations.CreateModel(
            name='PersonaRolEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rol_evento_documento', to='esclavizados.documento')),
                ('personas', models.ManyToManyField(related_name='p_roles_evento', to='esclavizados.persona')),
                ('rol_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_evento_personas', to='esclavizados.rolevento')),
            ],
        ),
        migrations.AddField(
            model_name='historicalpersonalugarrel',
            name='situacion_lugar',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esclavizados.situacionlugar'),
        ),
        migrations.AddField(
            model_name='personalugarrel',
            name='situacion_lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situacion_lugar', to='esclavizados.situacionlugar'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_documento', to='esclavizados.tipodocumental'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esclavizados.tipodocumental'),
        ),
        migrations.CreateModel(
            name='HistoricalCorporacion',
            fields=[
                ('corporacion_id', models.IntegerField(blank=True, db_index=True)),
                ('corporacion_idno', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_institucion', models.CharField(db_index=True, max_length=100)),
                ('nombres_alternativos', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('tipo_institucion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esclavizados.tiposinstitucion')),
            ],
            options={
                'verbose_name': 'historical corporacion',
                'verbose_name_plural': 'historical corporacions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='HistoricalPlaceHistorical',
        ),
        migrations.DeleteModel(
            name='PlaceHistorical',
        ),
    ]
