# Generated by Django 5.0 on 2023-12-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaObject',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ca_objects',
            },
        ),
    ]
