# Generated by Django 5.0 on 2023-12-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caobject',
            options={'managed': False},
        ),
    ]
