# Generated by Django 5.0 on 2023-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_caobject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaEntityLabel',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_id', models.IntegerField()),
                ('locale_id', models.SmallIntegerField()),
                ('type_id', models.IntegerField(null=True)),
                ('displayname', models.CharField(max_length=512)),
                ('forename', models.CharField(max_length=100)),
                ('other_forenames', models.CharField(max_length=100, null=True)),
                ('middlename', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=512)),
                ('prefix', models.CharField(max_length=100, null=True)),
                ('suffix', models.CharField(max_length=100, null=True)),
                ('name_sort', models.CharField(max_length=512)),
                ('source_info', models.TextField()),
                ('is_preferred', models.PositiveSmallIntegerField()),
                ('sdatetime', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('edatetime', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('access', models.PositiveSmallIntegerField(default=0)),
                ('checked', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'ca_entity_labels',
                'managed': False,
            },
        ),
    ]
