# Generated by Django 5.0 on 2024-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopographic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bautismo',
            name='notas_fecha',
            field=models.CharField(blank=True, help_text='Fechas incompletas, incorrectas o anotaciones.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entierro',
            name='notas_fecha',
            field=models.CharField(blank=True, help_text='Fechas incompletas, incorrectas o anotaciones.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbautismo',
            name='notas_fecha',
            field=models.CharField(blank=True, help_text='Fechas incompletas, incorrectas o anotaciones.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalentierro',
            name='notas_fecha',
            field=models.CharField(blank=True, help_text='Fechas incompletas, incorrectas o anotaciones.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmatrimonio',
            name='notas_fecha',
            field=models.CharField(blank=True, help_text='Fechas incompletas, incorrectas o anotaciones.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersona',
            name='notas_fecha',
            field=models.CharField(blank=True, help_text='Fechas incompletas, incorrectas o anotaciones.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='notas_fecha',
            field=models.CharField(blank=True, help_text='Fechas incompletas, incorrectas o anotaciones.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='notas_fecha',
            field=models.CharField(blank=True, help_text='Fechas incompletas, incorrectas o anotaciones.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entierro',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha normalizada del documento'),
        ),
        migrations.AlterField(
            model_name='historicalentierro',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha normalizada del documento'),
        ),
    ]
