# Generated by Django 5.0 on 2024-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopographic', '0003_rename_notas_fecha_bautismo_notas_fecha_bautismo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='condicion_documento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='condicion_documento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
