# Generated by Django 5.0 on 2024-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopographic', '0004_alter_documento_condicion_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallugar',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
