# Generated by Django 5.0.2 on 2024-02-15 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopographic', '0006_entierro_conyuge_import_id_entierro_madre_import_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entierro',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entierros_como_lugar', to='prosopographic.lugar'),
        ),
        migrations.AlterField(
            model_name='entierro',
            name='tipo_de_entierro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentierro',
            name='tipo_de_entierro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
