# Generated by Django 5.0.2 on 2024-02-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopographic', '0007_alter_entierro_lugar_alter_entierro_tipo_de_entierro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entierro',
            name='auxilio_espiritual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentierro',
            name='auxilio_espiritual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
